### PR TITLE
[native] Fix uuid constructor to make presto native work with boost 1.86

### PR DESCRIPTION
**Pull request by pansatadru**
## Description
Preto-Native build is failing with boost 1.86 with the following error:

presto_cpp/main/CMakeFiles/presto_server_lib.dir/TaskManager.cpp.o -c /Users/satadru/gitcode/presto/presto-native-execution/presto_cpp/main/TaskManager.cpp
/Users/satadru/gitcode/presto/presto-native-execution/presto_cpp/main/TaskManager.cpp:1041:13: error: call to implicitly-deleted default constructor of 'UuidParse'
  UuidParse uuid;
            ^
/Users/satadru/gitcode/presto/presto-native-execution/presto_cpp/main/TaskManager.cpp:1037:24: note: default constructor of 'UuidParse' is implicitly deleted because variant field 'uuid' has a non-trivial default constructor
    boost::uuids::uuid uuid;
                       ^
1 error generated.

## Motivation and Context
This diff fixes the constructor for UuidParse union to fix the build with boost 1.86. 

## Impact
Presto-Native should build with boost 1.86

## Test Plan
Build with both boost 1.85 and 1.86 pass. 

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

### CODE REVIEW

**Comment by amitkdutta** [comment]
Thanks @pansatadru. Please update the PR description.

- Contribution checklist: We can remove those as long as you checked those
- If there is no specific release notes, only keep no release notes part.

**Comment by zuyu** [comment]
Duplicate of #23469.

I like your fix, but no needs of `()`. `UuidParse uuid = {boost::uuids::random_generator()()};` should work.

**Comment by amitkdutta** [comment]
@pansatadru @kgpai @kevinwilfong  We should check what boost version Meta is running internally.

**Comment by kgpai** [comment]
@amitkdutta Should be a backwards compatible fix.

**Comment by spershin** [comment]
It builds well.
Just some weird formatting issue.
It somehow does not like the empty line?

**Comment by zuyu** [comment]
If the changes backward works w/ 1.85, then just approve #23469?

**Comment by nmahadevuni** [comment]
@pansatadru Can we close this in favour of https://github.com/prestodb/presto/pull/23469 ?

**Comment by pansatadru** [comment]
@nmahadevuni @zuyu : Sure thing. Let me close this one in favor of https://github.com/prestodb/presto/pull/23469 Thanks.
