### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Broken with commit 2bbdb43542044edcbb6cde8dd90af4a784087a2f

### CODE REVIEW

**Comment by electrum** [comment]
Thanks, my fault, there was a logical merge conflict. I should have re-ran Travis before merging the PR.
