### ISSUE TITLE
UT failures in presto-kafka module when upgrading org.apache.zookeeper from 3.4.14 to 3.7.2

### ISSUE THREAD

**Issue by SusanPhilip** [prestodb/presto#21950]
Unable to upgrade zookeeper version. Kafka has a dependency with zookeeper so upgrading zookeeper leads to UT failures in kakfa. Upgrading kafka to a compatible version version of zookeeper leads to break in code compilation as many classes are not found. 

PR associated with the same: https://github.com/prestodb/presto/pull/21119

## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Errors faced
com.facebook.presto.kafka.TestMinimalFunctionality.startKafka  Time elapsed: 5.491 s  <<< FAILURE!
java.lang.NoClassDefFoundError: com.codahale.metrics.Reservoir
com.facebook.presto.kafka.TestMinimalFunctionality.tearDown  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.NullPointerException

**While upgrading kafka the below errors were shown:**
presto/presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java: cannot find symbol class ZkUtils
 symbol:   class 
location: package kafka.utils
presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java:[127,9] cannot find symbol class 
 symbol:   class ZkUtils
 location: class com.facebook.presto.kafka.util.EmbeddedKafka

**Comment by Akanksha-kedia** [comment]
https://github.com/prestodb/presto/pull/21957
