### PR TITLE
UT failures in presto-kafka module when upgrading org.apache.zookeeper from 3.4.14 to 3.7.2

### PR DESCRIPTION
**Pull request by Akanksha-kedia**
## Description
UT failures in presto-kafka module when upgrading org.apache.zookeeper from 3.4.14 to 3.7.2

## Motivation and Context
Unable to upgrade zookeeper version. Kafka has a dependency with zookeeper so upgrading zookeeper leads to UT failures in kakfa. Upgrading kafka to a compatible version version of zookeeper leads to break in code compilation as many classes are not found.

PR associated with the same: https://github.com/prestodb/presto/pull/21119

## Impact
Your Environment
Presto version used:
Storage (HDFS/S3/GCS..):
Data source and connector used:
Deployment (Cloud or On-prem):
[Pastebin](https://pastebin.com/) link to the complete debug logs:

## Test Plan:

REMOVE THE ERROR
Errors faced
com.facebook.presto.kafka.TestMinimalFunctionality.startKafka Time elapsed: 5.491 s <<< FAILURE!
java.lang.NoClassDefFoundError: com.codahale.metrics.Reservoir
com.facebook.presto.kafka.TestMinimalFunctionality.tearDown Time elapsed: 0.002 s <<< FAILURE!
java.lang.NullPointerException

While upgrading kafka the below errors were shown:
presto/presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java: cannot find symbol class ZkUtils
symbol: class
location: package kafka.utils
presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java:[127,9] cannot find symbol class
symbol: class ZkUtils
location: class com.facebook.presto.kafka.util.EmbeddedKafka

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* Upgrade kafka client.
```

### CODE REVIEW

**Comment by Akanksha-kedia** [comment]
I have used same commit msg used for issue creation, will explain anyways its in work in progress state.

**Comment by steveburnett** [comment]
Please be more specific in the release note entry to help a future person reading the release note understand what was done - perhaps something like: 

```
== RELEASE NOTES ==

General Changes
* Upgrade kafka client to 3.3.2.
```
